"""Vault graph v2: concepts, layered structure, graph-aware retrieval, report helpers, export hygiene.

Real store and real sentence embeddings (CPU); the report writer end-to-end test uses the local `small` model.
"""

from __future__ import annotations

import json
import os

import numpy as np
import pytest

from aof.config import MemoryConfig, load_config, resolve_role_path
from aof.memory.store import MemoryStore
from aof.memory.zettel import ZettelNote
from aof.refine.concepts import acronym_definitions, candidate_phrases, extract_concepts, related_concepts
from aof.refine.embcache import EmbeddingCache, cached_embedder
from aof.refine.export import export_vault
from aof.refine.graph import GraphOptions, broader_concepts, build_graph, collect_sources, mutual_knn
from aof.refine.hubs import hub_tree, kmeans_split
from aof.refine.metrics import graph_shape
from aof.refine.report import (
    ReportOptions, ReportState, ReportWriter, SectionDraft, SectionPlan, clean_citations, cited_sentences,
    parse_outline,
)
from aof.refine.retrieve import VaultGraph
from aof.specialists import build_registry

CONFIG = load_config("config.toml")

# Three topics, two papers each, with the vocabulary a real abstract would use.
PAPERS = {
    "trn-a": ("The thalamic reticular nucleus (TRN) in sensory gating (2019)", [
        "The thalamic reticular nucleus (TRN) is a shell of GABAergic neurons surrounding the dorsal thalamus.",
        "TRN neurons receive collaterals from corticothalamic and thalamocortical axons.",
        "The TRN projects to thalamic relay nuclei but not to the neocortex.",
    ]),
    "trn-b": ("Sleep spindles and the TRN (2021)", [
        "Sleep spindles are generated by interactions between TRN neurons and thalamocortical relay neurons.",
        "T-type calcium channels in TRN neurons produce rhythmic burst firing during sleep spindles.",
        "Optogenetic stimulation of the TRN induces sleep spindles in mice.",
    ]),
    "grid-a": ("Grid cells of the medial entorhinal cortex (2015)", [
        "Grid cells in the medial entorhinal cortex fire at the vertices of a hexagonal lattice.",
        "Grid cells are organised in modules with discrete spatial scales along the dorsoventral axis.",
        "Grid cells are thought to support path integration during spatial navigation.",
    ]),
    "grid-b": ("Place cells and grid cells in navigation (2018)", [
        "Place cells in hippocampal area CA1 fire when an animal occupies a specific location.",
        "Place cells remap when the environment changes while grid cells keep their spatial scale.",
        "Head direction cells and grid cells together support spatial navigation.",
    ]),
    "swr-a": ("Sharp-wave ripples and memory consolidation (2016)", [
        "Sharp-wave ripples are high-frequency oscillations in CA1 during quiet wakefulness and sleep.",
        "Hippocampal replay of place cells occurs during sharp-wave ripples.",
        "Closed-loop disruption of sharp-wave ripples impairs spatial memory consolidation in rats.",
    ]),
    "swr-b": ("Coupling of ripples and sleep spindles (2020)", [
        "Sharp-wave ripples are nested in sleep spindles during memory consolidation.",
        "Ripples in CA1 are driven by synchronous bursts of CA3 pyramidal neurons.",
        "Reverse replay of place cells follows a run on a linear track.",
    ]),
}


def _claim_content(sentence: str, title: str, url: str) -> str:
    cite, year = title.rsplit(" (", 1)
    return f'{sentence}\n\n**Evidence**\n- "{sentence}" — {cite} ({year.rstrip(")")}), {url}'


@pytest.fixture
async def vault(tmp_path):
    store = MemoryStore(MemoryConfig(db_path=str(tmp_path / "m.db"), notes_dir=str(tmp_path / "notes")))
    await store.initialize()
    registry = build_registry(CONFIG, get_backend=None)
    embed = cached_embedder(registry, tmp_path)
    if embed is None:
        pytest.skip("sentence-transformers not available")
    try:
        await embed(["probe"])
    except Exception as e:
        pytest.skip(f"embedding model unavailable: {e}")
    for key, (title, sentences) in PAPERS.items():
        url = f"https://doi.org/10.1000/{key}"
        for i, s in enumerate(sentences):
            await store.create_note(s[:80], _claim_content(s, title, url), ["claim"], note_id=f"c-{key}-{i}",
                                    kind="claim", status="refined", sources=[url])
    yield store, registry, embed, tmp_path
    await registry.close()
    await store.close()


# ---------------------------------------------------------------- concepts (tier 0, deterministic)

def test_candidate_phrases_skip_generic_edges_and_fold_plurals():
    keys = candidate_phrases("These results suggest that place cells and grid cells support navigation.")
    assert "place cell" in keys and "grid cell" in keys
    assert not any(k.startswith(("result", "suggest")) for k in keys)
    assert "support" not in keys and "cell" not in keys  # verbs and generic nouns are never concepts alone


def test_acronyms_merge_into_their_expansion_when_defined_twice():
    texts = [
        "The thalamic reticular nucleus (TRN) gates sensory input.",
        "Neurons of the thalamic reticular nucleus (TRN) are GABAergic.",
        "The medial dorsolateral (MD) region appears once only.",
    ]
    defs = acronym_definitions(texts)
    assert defs["TRN"] == "thalamic reticular nucleu" or defs["TRN"].startswith("thalamic reticular")
    assert "MD" not in defs  # a single definition could be a coincidence of initials


def test_extract_concepts_on_the_fixture_sentences():
    items = [(f"{k}-{i}", s) for k, (_, ss) in PAPERS.items() for i, s in enumerate(ss)]
    concepts, assigned = extract_concepts(items, min_df=2, max_share=0.5)
    labels = {c.label.lower() for c in concepts}
    assert {"grid cells", "place cells", "sleep spindles", "sharp-wave ripples"} <= labels | {"sharp wave ripples"}
    assert any(c.key.lower() == "trn" or "reticular" in c.key for c in concepts)
    assert all(len(v) <= 3 for v in assigned.values())
    related = related_concepts(concepts, assigned, min_pair=1)
    assert related  # co-mentioned concepts are related


def test_broader_concepts_by_contained_phrase():
    from aof.refine.concepts import Concept

    cs = [Concept("entorhinal cortex", "entorhinal cortex"), Concept("medial entorhinal cortex", "MEC"),
          Concept("grid cell", "grid cells")]
    assert broader_concepts(cs) == {"medial entorhinal cortex": "entorhinal cortex"}


# ---------------------------------------------------------------- hubs: balanced splits

def test_kmeans_split_is_balanced_and_hub_tree_caps_hub_size():
    rng = np.random.default_rng(0)
    centre = rng.normal(size=16)
    notes, vectors = [], {}
    for i in range(300):  # one dense blob: threshold clustering alone cannot split it
        nid = f"n{i:03d}"
        notes.append(ZettelNote(id=nid, title=nid, content=f"claim {i}", kind="claim"))
        vectors[nid] = (centre + 0.35 * rng.normal(size=16)).tolist()
    parts = kmeans_split(notes, vectors, 4)
    assert len(parts) == 4 and min(len(p) for p in parts) >= 30
    tree = hub_tree(notes, vectors, threshold=0.5, min_size=3, max_size=40)

    def leaves(nodes):
        for n in nodes:
            yield from (leaves(n.children) if n.children else [n])

    assert max(len(leaf.members) for leaf in leaves(tree)) <= 60


# ---------------------------------------------------------------- the graph pass

async def test_build_graph_layers_and_idempotence(vault):
    store, registry, embed, _ = vault
    opts = GraphOptions(concept_min_df=2, concept_max_share=0.5, hub_min_size=2, max_hub_size=6, link_min_sim=0.4)
    report = await build_graph(store, None, embed, opts)
    assert report.claims == 18 and report.sources == 6 and report.concepts >= 4 and report.hubs >= 2

    claim = await store.get_note("c-trn-b-0")
    kinds = {}
    for link in claim.links:
        kinds.setdefault((await store.get_note(link)).kind, []).append(link)
    assert kinds.get("source") and kinds.get("concept") and kinds.get("hub")
    for other in kinds.get("claim", []):  # claim-claim links join different papers only (same paper = source note)
        assert not other.startswith("c-trn-b-")

    src = await store.get_note(kinds["source"][0])
    assert src.kind == "source" and "Sleep spindles and the TRN" in src.title and len(src.links) == 3
    concept = await store.get_note(kinds["concept"][0])
    assert concept.kind == "concept" and "claim" not in concept.tags and "c-trn-b-0" in concept.links

    again = await build_graph(store, None, embed, opts)
    assert again.claims_changed == 0  # nothing derived changed: idempotent

    shape = graph_shape([*(await store.get_notes_by_tags(["claim", "hub", "concept", "source"], limit=1000))])
    assert shape["isolated_nodes"] == 0 and shape["duplicate_hub_titles"] == 0
    assert shape["claims_with_concept"] > 0.8


def test_mutual_knn_skips_same_work_and_near_duplicates():
    notes = [ZettelNote(id=x, title=x, content=x) for x in "abcd"]
    vecs = {"a": [1.0, 0.0, 0.0], "b": [0.9, 0.3, 0.0], "c": [0.8, 0.5, 0.1], "d": [1.0, 0.0001, 0.0]}
    works = {"a": {"w1"}, "b": {"w1"}, "c": {"w2"}, "d": {"w3"}}
    edges = mutual_knn(notes, vecs, k=2, min_sim=0.5, max_sim=0.99, same_work=works)
    assert "b" not in edges["a"]  # same paper
    assert "d" not in edges["a"]  # cosine ~1.0: a duplicate, not a relation
    assert all(x in edges[y] for x, ys in edges.items() for y in ys)  # mutual


def test_collect_sources_reads_titles_and_years_from_evidence():
    n = ZettelNote(id="x", title="t", content=_claim_content("A claim.", "Some paper (2011)", "https://doi.org/10.1/x"),
                   sources=["https://doi.org/10.1/x"])
    works = collect_sources([n])
    (info,) = works.values()
    assert info.title == "Some paper" and info.year == "2011" and info.label == "Some paper (2011)"


# ---------------------------------------------------------------- retrieval

async def test_retrieval_spreads_through_concepts_and_caps_each_work(vault):
    store, _, embed, _ = vault
    await build_graph(store, None, embed, GraphOptions(concept_min_df=2, concept_max_share=0.5, hub_min_size=2,
                                                       max_hub_size=6))
    graph = await VaultGraph(store, embed).load()
    got = await graph.retrieve(["How do sleep spindles relate to the thalamic reticular nucleus?"], k=6, per_work=2)
    works = [e.source_url for e in got]
    assert got and max(works.count(w) for w in works) <= 2
    assert any("spindle" in e.text.lower() for e in got[:3])
    assert got[0].source_label.endswith(")") and got[0].concepts

    first = {e.note_id for e in got}
    again = await graph.retrieve(["sleep spindles thalamic reticular nucleus"], k=6, per_work=2, used=first,
                                 used_penalty=1.0)
    assert not ({e.note_id for e in again} & first) or len(again) < 6  # used claims are pushed down
    budgeted = await graph.retrieve(["grid cells"], k=20, token_budget=60)
    assert 1 <= len(budgeted) <= 3
    vmap = await graph.vault_map(["grid cells and place cells"], hubs=3, concepts=5)
    assert {m.kind for m in vmap} == {"hub", "concept"}


async def test_embedding_cache_hits_on_second_call(tmp_path):
    calls = []

    async def fake_embed(texts):  # counts calls; vectors are deterministic
        calls.append(list(texts))
        return [[float(len(t)), 1.0] for t in texts]

    cache = EmbeddingCache(tmp_path / "e.db", "m")
    embed = cache.wrap(fake_embed)
    assert await embed(["a", "bb"]) == [[1.0, 1.0], [2.0, 1.0]]
    assert await embed(["bb", "ccc"]) == [[2.0, 1.0], [3.0, 1.0]]
    assert calls == [["a", "bb"], ["ccc"]] and cache.hits == 1
    cache.close()


# ---------------------------------------------------------------- report helpers (deterministic)

def test_parse_outline_tolerates_markdown_and_numbering():
    text = (
        "**TITLE:** The TRN in sleep and attention\n\n"
        "SECTION: 1. Anatomy of the TRN\nFOCUS: What is the TRN made of?\nQUERIES: TRN GABAergic shell | TRN inputs\n"
        "SECTION: Spindle generation\nFOCUS: How does the TRN generate spindles?\nQUERIES: spindles TRN; T-type\n"
        "SECTION: Attention\nQUERIES: attentional gating TRN\n"
    )
    title, plans = parse_outline(text.replace("**TITLE:**", "TITLE:"), 5)
    assert title == "The TRN in sleep and attention"
    assert [p.title for p in plans] == ["Anatomy of the TRN", "Spindle generation", "Attention"]
    assert plans[1].queries == ["spindles TRN", "T-type"] and plans[2].focus == "Attention"


def test_clean_citations_and_cited_sentences():
    text = "TRN is GABAergic [1, 9]. It gates input [2-3]. Unsupported claim. Spindles [7]."
    cleaned, removed = clean_citations(text, {1, 2, 3})
    assert cleaned == "TRN is GABAergic [1]. It gates input [2, 3]. Unsupported claim. Spindles." and removed == 2
    sents = cited_sentences(cleaned)
    assert [n for _, n in sents] == [[1], [2, 3], [], []]


def test_outline_drops_frame_sections_and_prose_is_cleaned():
    from aof.refine.report import clean_prose

    titles = ["Introduction", "Anatomy", "Spindles", "Attention", "Synthesis of TRN functions", "Conclusions"]
    text = "".join(f"SECTION: {t}\nFOCUS: f\n" for t in titles)
    _, plans = parse_outline(text, 9)
    assert [p.title for p in plans] == ["Anatomy", "Spindles", "Attention"]
    prose = ("I am Qwythos, an AI model created by Empero AI. The TRN is GABAergic [1]. It gates relay [2]. "
             "The TRN is GABAergic [3].\n\n   Indented paragraph starts here [4].")
    assert clean_prose(prose) == "The TRN is GABAergic [1]. It gates relay [2].\n\nIndented paragraph starts here [4]."
    assert clean_prose("Sure, here is the section:\nSpindles arise in the TRN [1].") == "Spindles arise in the TRN [1]."


def test_render_renumbers_by_first_appearance_and_links_claims(tmp_path):
    state = ReportState("topic", title="T", plan=[SectionPlan("A", "a?"), SectionPlan("B", "b?")])
    state.numbering = {"c1": 5, "c2": 2, "c3": 9}
    for cid in state.numbering:
        state.evidence[cid] = {"text": f"text {cid}", "source_label": f"Paper {cid} (2020)", "source_url": f"https://x/{cid}"}
    state.drafts = [SectionDraft("A", text="First [5]. Second [2, 5]."), SectionDraft("B", text="Third [9].")]
    writer = ReportWriter.__new__(ReportWriter)
    writer.opt = ReportOptions()
    md = writer.render(state, wikilinks=True)
    assert "First [1]. Second [1, 2]." in md and "Third [3]." in md
    refs = md.split("## References", 1)[1]
    assert refs.index("text c1") < refs.index("text c2") < refs.index("text c3")
    assert "[[c1|" in refs
    plain = writer.render(state, wikilinks=False)
    assert "[[" not in plain


# ---------------------------------------------------------------- export hygiene

async def test_export_removes_stale_files_and_keeps_user_graph_settings(vault):
    store, _, embed, tmp = vault
    await build_graph(store, None, embed, GraphOptions(concept_min_df=2, concept_max_share=0.5, hub_min_size=2,
                                                       max_hub_size=6))
    out = tmp / "export"
    (out / "claims").mkdir(parents=True)
    (out / "claims" / "stale note.md").write_text("---\nid: gone\n---\n", encoding="utf-8")
    (out / ".obsidian").mkdir()
    (out / ".obsidian" / "graph.json").write_text('{"mine": true}', encoding="utf-8")
    counts = await export_vault(store, out)
    assert not (out / "claims" / "stale note.md").exists()
    assert json.loads((out / ".obsidian" / "graph.json").read_text(encoding="utf-8")) == {"mine": True}
    assert counts["claims"] == 18 and counts["concepts"] >= 4 and counts["sources"] == 6
    concept_file = next((out / "concepts").iterdir()).read_text(encoding="utf-8")
    assert "Concept: **" in concept_file and "[[" in concept_file
    claim_file = next((out / "claims").iterdir()).read_text(encoding="utf-8")
    assert "**Source:**" in claim_file and "**Concepts:**" in claim_file


# ---------------------------------------------------------------- end to end with a real model

needs_small = pytest.mark.skipif(
    not os.path.exists(resolve_role_path(CONFIG, "small")), reason="local small role model not available"
)


@needs_small
async def test_report_writer_end_to_end_with_small_model(vault):
    from aof.specialists.backends import RoleBackends
    from aof.specialists.role_provider import RoleProvider

    store, registry, embed, tmp = vault
    await build_graph(store, None, embed, GraphOptions(concept_min_df=2, concept_max_share=0.5, hub_min_size=2,
                                                       max_hub_size=6))
    backends = RoleBackends(CONFIG)
    judge_provider = RoleProvider("small", CONFIG, backends.get)

    async def generate(system, user, max_tokens):
        from aof.inference.parsing import parse_response

        b = await backends.get("small")
        r = await b.complete([{"role": "system", "content": system}, {"role": "user", "content": user}],
                             temperature=0.3, max_tokens=max_tokens)
        return parse_response(r.text).text

    async def judge(statement, evidence):
        r = await judge_provider.judge(statement, evidence)
        return r.value["verdict"] if r else "needs_lookup"

    steered = []

    async def control():
        if not steered:
            steered.append(1)
            return ["Mention species where the evidence names them."]
        return []

    try:
        graph = await VaultGraph(store, embed).load()
        writer = ReportWriter(
            store, graph, generate, judge=judge, confirm=None, workspace_root=tmp, control=control,
            options=ReportOptions(sections=3, ctx_tokens=CONFIG.role_context.get("small", 4096), section_words=150,
                                  section_out_tokens=500, min_evidence=2),
            writer_name="small",
        )
        state = await writer.run("How do sleep, the TRN and hippocampal ripples relate?")
    finally:
        await backends.close()

    assert state.stage == "done" and len(state.drafts) >= 3 and all(d.text for d in state.drafts)
    assert "Mention species where the evidence names them." in state.guidance  # steering picked up mid-run
    md = (tmp / "reports" / "how-do-sleep-the-trn-and-hippocampal-ripples-relate.md").read_text(encoding="utf-8")
    import re

    assert md.startswith("# ") and "## References" in md and re.search(r"\[1[\],]", md)
    assert "\n1. “" in md.split("## References", 1)[1]  # the first reference quotes its claim
    from aof.refine.report import report_note_id

    note = await store.get_note(report_note_id(state.topic))
    assert note is not None and note.kind == "report" and note.links and all(l.startswith("c-") for l in note.links)
    # resuming a finished report does not rewrite it
    again = await ReportWriter(store, graph, generate, workspace_root=tmp, options=writer.opt).run(state.topic)
    assert [d.text for d in again.drafts] == [d.text for d in state.drafts]
