"""Links, hubs, metrics and export on a small multi-topic vault (real store, real sentence embeddings, CPU only)."""

from __future__ import annotations

import pytest

from aof.config import MemoryConfig, load_config
from aof.memory.store import MemoryStore
from aof.refine.export import export_vault
from aof.refine.hubs import build_hubs, cluster_notes, keyword_title
from aof.refine.link import apply_links, propose_links, specific_entities
from aof.refine.metrics import compute_metrics, measure
from aof.refine.pipeline import registry_embedder
from aof.refine.verify import claim_text
from aof.specialists import build_registry

TRN = [
    "The thalamic reticular nucleus is a shell of GABAergic neurons surrounding the dorsal thalamus.",
    "TRN neurons receive collaterals from corticothalamic and thalamocortical axons.",
    "The TRN projects to thalamic relay nuclei but not to the neocortex.",
    "Sleep spindles are generated by interactions between TRN and thalamocortical relay neurons.",
    "T-type calcium channels in TRN neurons produce rhythmic burst firing during NREM sleep.",
]
GRID = [
    "Grid cells in medial entorhinal cortex fire at the vertices of a hexagonal lattice.",
    "Grid cells are organised in modules with discrete spatial scales along the dorsoventral axis.",
    "Place cells in hippocampal area CA1 fire when an animal occupies a specific location.",
    "Head direction cells signal the facing direction of the animal independent of location.",
    "Entorhinal grid cells are thought to support path integration during spatial navigation.",
]
SWR = [
    "Sharp-wave ripples are high-frequency oscillations in CA1 during quiet wakefulness and NREM sleep.",
    "Hippocampal replay reactivates place cell sequences during sharp-wave ripples.",
    "Closed-loop disruption of ripples impairs spatial memory consolidation in rats.",
    "Ripples in CA1 are driven by synchronous bursts of CA3 pyramidal neurons.",
    "Reverse replay of place cell sequences occurs at the end of a run on a track.",
]
TOPICS = {"trn": TRN, "grid": GRID, "swr": SWR}


@pytest.fixture
async def vault(tmp_path):
    store = MemoryStore(MemoryConfig(db_path=str(tmp_path / "m.db"), notes_dir=str(tmp_path / "notes")))
    await store.initialize()
    config = load_config("config.toml")
    registry = build_registry(config, get_backend=None)  # only the embedding provider is used here
    embed = registry_embedder(registry)
    if embed is None:
        pytest.skip("sentence-transformers not available")
    notes = []
    for topic, sentences in TOPICS.items():
        for i, s in enumerate(sentences):
            tags = ["claim", f"topic-{topic}"] + (["entity:trn"] if topic == "trn" else [])
            notes.append(await store.create_note(
                s, f"{s}\n\n**Evidence**\n- \"{s}\" — T, https://example.org/{topic}/{i}", tags,
                note_id=f"c-{topic}-{i}", kind="claim", status="refined",
                sources=[f"https://example.org/{topic}/{i}", f"https://pubmed.example/{topic}/{i}"] if i == 0 else [f"https://example.org/{topic}/{i}"],
            ))
    try:
        vectors = dict(zip((n.id for n in notes), await embed([claim_text(n) for n in notes])))
    except Exception as e:
        pytest.skip(f"embedding model unavailable: {e}")
    yield store, notes, vectors, registry
    await registry.close()
    await store.close()


def _topic(note_id: str) -> str:
    return note_id.split("-")[1]


async def test_links_are_mutual_and_stay_mostly_within_a_topic(vault):
    store, notes, vectors, _ = vault
    links = propose_links(notes, vectors, min_sim=0.45)
    assert all(a in links[b] for a, ls in links.items() for b in ls), "links must be mutual"
    edges = [(a, b) for a, ls in links.items() for b in ls if a < b]
    assert edges, "expected some related claims to be linked"
    within = sum(1 for a, b in edges if _topic(a) == _topic(b))
    assert within / len(edges) >= 0.75, edges

    changed = await apply_links(store, notes, links)
    assert changed > 0
    reloaded = await store.get_note("c-trn-2")
    assert set(reloaded.links) == links["c-trn-2"]
    assert await apply_links(store, [reloaded], links) == 0  # idempotent


def test_near_duplicates_are_not_linked_and_ubiquitous_entities_are_ignored():
    from aof.memory.zettel import ZettelNote

    notes = [ZettelNote(id=f"n{i}", title="t", content="c", tags=["entity:trn"] + ([f"entity:rare"] if i < 2 else []))
             for i in range(6)]
    assert specific_entities(notes) == {"rare"}  # 'trn' is on every note: no signal
    vecs = {"n0": [1.0, 0.0], "n1": [0.999, 0.04], "n2": [0.0, 1.0], "n3": [0.0, 1.0], "n4": [1.0, 1.0], "n5": [0.0, 1.0]}
    links = propose_links(notes[:2], vecs, min_sim=0.1)
    assert links["n0"] == set() and links["n1"] == set()  # cosine ~1.0 => duplicate, not a relation


async def test_clusters_recover_the_topics_and_hubs_are_extractive(vault):
    store, notes, vectors, _ = vault
    await apply_links(store, notes, propose_links(notes, vectors, min_sim=0.45))
    live = [await store.get_note(n.id) for n in notes]
    groups = cluster_notes(live, vectors, threshold=0.4, min_size=3)
    assert groups
    for g in groups:  # each hub is dominated by one topic
        top = max({_topic(n.id) for n in g}, key=lambda t: sum(_topic(n.id) == t for n in g))
        assert sum(_topic(n.id) == top for n in g) / len(g) >= 0.7, [n.id for n in g]

    hubs = await build_hubs(store, live, vectors, registry=None, threshold=0.4)
    assert len(hubs) == len(groups)
    for hub in hubs:
        assert hub.kind == "hub" and hub.status == "canonical" and hub.title
        for member_id in hub.links:
            member = await store.get_note(member_id)
            assert hub.id in member.links  # members link back
            assert claim_text(member) in hub.content  # extractive: the claim text itself, no new prose
    again = await build_hubs(store, [await store.get_note(n.id) for n in notes], vectors, registry=None, threshold=0.4)
    assert sorted(h.id for h in again) == sorted(h.id for h in hubs)  # idempotent: same hubs, refreshed
    assert len(await store.get_notes_by_tags(["hub"], exclude_tags=["archived"])) == len(hubs)


def test_keyword_title_uses_member_vocabulary():
    from aof.memory.zettel import ZettelNote

    members = [ZettelNote(id=str(i), title="t", content=s) for i, s in enumerate(TRN)]
    title = keyword_title(members)
    assert title and any(w.lower() in " ".join(TRN).lower() for w in title.split())


async def test_metrics_improve_after_linking_and_hubs(vault):
    store, notes, vectors, registry = vault
    before = await compute_metrics(store, registry)
    assert before.live_claims == 15 and before.hubs == 0
    assert before.orphan_rate == 1.0 and before.hub_coverage == 0.0
    assert before.sourced_rate == 1.0
    assert before.corroborated_rate == pytest.approx(3 / 15)  # only each topic's first note has two sources

    await apply_links(store, notes, propose_links(notes, vectors, min_sim=0.45))
    live = [await store.get_note(n.id) for n in notes]
    await build_hubs(store, live, vectors, registry=None, threshold=0.4)
    after = await compute_metrics(store, registry)
    assert after.orphan_rate < before.orphan_rate
    assert after.hub_coverage > 0.6 and after.avg_links > before.avg_links and after.hubs >= 2
    assert "example.org" in after.source_mix
    assert "orphan rate" in after.render()


def test_measure_counts_duplicates_and_conflicts():
    from aof.memory.zettel import ZettelNote

    a = ZettelNote(id="a", title="t", content="x", sources=["https://x.org/1"], tags=["claim"])
    b = ZettelNote(id="b", title="t", content="x", sources=["https://x.org/2"], tags=["claim", "conflict"])
    m = measure([a, b], archived=3, hubs=[], vectors={"a": [1.0, 0.0], "b": [1.0, 0.0]})
    assert m.duplicate_rate == 0.5 and m.conflicts == 1 and m.archived == 3
    assert measure([], 0, []).live_claims == 0


async def test_export_is_lossless_and_wikilinked(vault, tmp_path):
    store, notes, vectors, _ = vault
    await apply_links(store, notes, propose_links(notes, vectors, min_sim=0.45))
    live = [await store.get_note(n.id) for n in notes]
    await build_hubs(store, live, vectors, registry=None, threshold=0.4)
    archived = await store.create_note(
        "old", "An archived duplicate sentence.", ["claim", "archived"], note_id="c-old", kind="claim",
        status="archived", sources=["https://example.org/old"],
    )
    archived.superseded_by = "c-trn-0"
    await store.update_note(archived)

    out = tmp_path / "export"
    counts = await export_vault(store, out, title="Test vault")
    assert counts["claims"] == 15 and counts["archive"] == 1 and counts["hubs"] >= 2
    assert (out / "archive" / "c-old.md").exists()  # nothing dropped from the export

    index = (out / "Index.md").read_text(encoding="utf-8")
    assert "# Test vault" in index and index.count("[[hub-") == counts["hubs"]
    text = (out / "claims" / "c-trn-0.md").read_text(encoding="utf-8")
    assert text.startswith("---\nid: c-trn-0\n") and 'status: refined' in text
    assert "sources:" in text and "https://pubmed.example/trn/0" in text
    hub_text = next((out / "hubs").iterdir()).read_text(encoding="utf-8")
    assert "[[c-" in hub_text and "|" in hub_text  # aliased wikilinks like [[id|readable title]]
    assert "Sources.md" and (out / "Sources.md").read_text(encoding="utf-8").count("https://") >= 15


# -- nested hubs and stale-hub retirement (crafted vectors: no model needed) ---------------------------------

def _crafted_vault():
    """Topic A = two subtopics with centre cosine ~0.55 (merge at 0.5, split at 0.62); topic B is separate."""
    import random

    from aof.memory.zettel import ZettelNote

    rng = random.Random(3)
    a = 0.904  # cos(A1, A2) = 1 / (1 + a^2) ~ 0.55
    dim = 12

    def vec(*pairs):
        v = [rng.gauss(0, 0.01) for _ in range(dim)]
        for axis, weight in pairs:
            v[axis] += weight
        return v

    notes, vectors = [], {}
    for i in range(40):
        for name, pairs in (("a1", [(0, 1.0), (2, a)]), ("a2", [(0, 1.0), (3, a)])):
            nid = f"{name}-{i}"
            notes.append(ZettelNote(id=nid, title=nid, content=f"{name} claim number {i} about topic a.", tags=["claim"], kind="claim"))
            vectors[nid] = vec(*pairs)
    for i in range(10):
        nid = f"b-{i}"
        notes.append(ZettelNote(id=nid, title=nid, content=f"b claim {i} about topic b.", tags=["claim"], kind="claim"))
        vectors[nid] = vec((1, 1.0))
    return notes, vectors


def test_large_hub_is_split_into_subtopic_hubs():
    from aof.refine.hubs import hub_tree

    notes, vectors = _crafted_vault()
    tree = hub_tree(notes, vectors, threshold=0.5, min_size=3, max_size=60, step=0.12)
    big = max(tree, key=lambda n: len(n.members))
    assert len(big.members) == 80 and len(big.children) == 2
    assert sorted(len(c.members) for c in big.children) == [40, 40]
    for child in big.children:  # each subtopic is pure
        assert len({n.id.split("-")[0] for n in child.members}) == 1
    small = min(tree, key=lambda n: len(n.members))
    assert small.children == [] and len(small.members) == 10


async def test_build_hubs_makes_a_tree_and_retires_stale_hubs(tmp_path):
    store = MemoryStore(MemoryConfig(db_path=str(tmp_path / "m.db"), notes_dir=str(tmp_path / "notes")))
    await store.initialize()
    try:
        crafted, vectors = _crafted_vault()
        notes = []
        for n in crafted:
            notes.append(await store.create_note(n.title, n.content, ["claim"], note_id=n.id, kind="claim", status="refined",
                                                 sources=[f"https://x.org/{n.id}"]))
        hubs = await build_hubs(store, notes, vectors, registry=None, threshold=0.5, max_hub_size=60)
        levels = sorted(next(t for t in h.tags if t.startswith("hub-level:")) for h in hubs)
        assert levels == ["hub-level:0", "hub-level:0", "hub-level:1", "hub-level:1"]
        parent = next(h for h in hubs if "hub-level:0" in h.tags and any(i.startswith("hub-1-") for i in h.links))
        assert "**Subtopics**" in parent.content and len([i for i in parent.links if i.startswith("hub-1-")]) == 2
        member = await store.get_note("a1-0")
        assert any(i.startswith("hub-1-") for i in member.links)  # linked to its most specific hub

        # Rebuilding from only topic B retires topic A's hubs (archived, not deleted) and unlinks their claims.
        only_b = [await store.get_note(n.id) for n in crafted if n.id.startswith("b-")]
        again = await build_hubs(store, only_b, {k: v for k, v in vectors.items() if k.startswith("b-")}, registry=None)
        live_ids = {h.id for h in await store.get_notes_by_tags(["hub"], exclude_tags=["archived"], limit=100)}
        assert live_ids == {h.id for h in again}
        old = await store.get_note(parent.id)
        assert old.status == "archived" and "archived" in old.tags
        assert not any(i.startswith("hub-") for i in (await store.get_note("a1-0")).links)
    finally:
        await store.close()


async def test_export_index_shows_every_hub_level(tmp_path):
    store = MemoryStore(MemoryConfig(db_path=str(tmp_path / "m.db"), notes_dir=str(tmp_path / "notes")))
    await store.initialize()
    try:
        crafted, vectors = _crafted_vault()
        notes = [
            await store.create_note(n.title, n.content, ["claim"], note_id=n.id, kind="claim", status="refined",
                                    sources=[f"https://x.org/{n.id}"])
            for n in crafted
        ]
        hubs = await build_hubs(store, notes, vectors, registry=None, threshold=0.5, max_hub_size=60)
        await export_vault(store, tmp_path / "out", title="Tree")
        index = (tmp_path / "out" / "Index.md").read_text(encoding="utf-8")
        parent = next(h for h in hubs if "hub-level:0" in h.tags and any(i.startswith("hub-1-") for i in h.links))
        child_lines = [ln for ln in index.splitlines() if "[[hub-1-" in ln]
        assert child_lines and all(ln.startswith("    - ") for ln in child_lines)  # nested one level under a parent
        assert f"[[{parent.id}|" in index and "80 claims" in index
    finally:
        await store.close()
